---
- hosts: mose-sandbosc
  gather_facts: no
  vars:
    zshprompt_fg_color: 7
    zshprompt_bg_color: 22
    username: mose
  roles:
    - role: freebsd
      become: true
      become_user: root
      become_method: sudo
    - shell
