---
- name: Disable ssh root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin No"

- name: Install ntp
  pkgng: name=ntp

- name: create empty rc.conf
  file: dest=/etc/rc.conf state=touch

- name: Enable ntp
  service: name=ntpd state=started enabled=yes

- name: Set auto update to daily
  lineinfile:
    dest: /etc/crontab
    regexp: freebsd-update cron
    line: "@daily                                  root    freebsd-update cron"

- name: Add proc to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: ^proc
    line: proc /proc procfs rw 0 0

- name: Add fdesc to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: ^fdesc
    line: fdesc /dev/fd fdescfs rw 0 0

- name: Mount all
  command: mount -a

- name: install various tools
  pkgng: name=zsh,vim-lite,curl,wget,git,subversion,rsync
         state=present

- name: tune {{ username }} user
  user: name={{ username }} shell=/usr/local/bin/zsh group=wheel


